name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
      - develop

jobs:
  deploy-master:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy master to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          cname: altstore-jp.bunchoniki.com
          keep_files: true

  deploy-develop:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy _config-dev.yml to _config.yml
        run: cp _config-dev.yml _config.yml

      - name: Deploy develop to gh-pages dev folder
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          destination_dir: dev
